### ISSUE TITLE
renomear repositório para hub-reply-bot

### ISSUE THREAD

**Issue by RodrigoDornelles** [aHub-Tech/twitch-hubble-bot#4]
se o bot for híbrido #2, contudo apenas responde mensagens de maneira simples, acho que o nome se enquadra melhor ao propósito.

**Comment by vcwild** [comment]
Resolvido! :wink:

**Comment by RodrigoDornelles** [comment]
Está bem fora de padrão dos outros repos da hub, estou reabrindo reconsiderando um novo nome! `hub-reply-bot`

**Comment by vcwild** [comment]
Tranquilo! Renomeado! Inclusive te coloquei como admin desse projeto.
